[project]
name = "po_viewer"
version = "0.1.0"
description = "A tool for viewing and checking PO (gettext) files"
requires-python = ">=3.8"
dependencies = [
    "polib",      # POファイルの解析用
    "rich",       # ターミナルでの表示を改善
    "typer",      # CLIインターフェース用
    "PySide6>=6.6.0",  # GUIインターフェース用
]

[project.scripts]
po-viewer-cli = "po_viewer.cli:app"
po-viewer = "po_viewer.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
